pktha/pengaduan/common/models/PengaduanMediasi.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "pengaduan_mediasi".
 *
 * @property string $id_pengaduan
 * @property string $data_para_pihak
 * @property string $pokok_permasalahan
 * @property string $objek_mediasi
 * @property string $proses_pertemuan
 * @property string $id
 * @property string $created_date
 * @property string $modified_date
 * @property boolean $finished
 * @property string $berita_acara_filename
 * @property string $foto_filename
 * @property string $surat_usulan_mediator_filename
 * @property string $sk_mediator_filename
 */
class PengaduanMediasi extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pengaduan_mediasi';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_pengaduan'], 'required'],
            [['id_pengaduan'], 'integer'],
            [['data_para_pihak', 'pokok_permasalahan', 'objek_mediasi', 'proses_pertemuan'], 'string'],
            [['berita_acara_filename', 'foto_filename', 'surat_usulan_mediator_filename', 'sk_mediator_filename'], 'file', 'extensions' => 'pdf, doc, docx, odt'],
            [['foto_filename'], 'file', 'extensions' => 'jpg, jpeg, bmp'],
            [['created_date', 'modified_date'], 'safe'],
            [['finished'], 'boolean'],
            [['id_pengaduan'], 'exist', 'skipOnError' => true, 'targetClass' => PengaduanRegistrasi::className(), 'targetAttribute' => ['id_pengaduan' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_pengaduan' => Yii::t('app', 'Id Pengaduan'),
            'data_para_pihak' => Yii::t('app', 'Data Para Pihak'),
            'pokok_permasalahan' => Yii::t('app', 'Pokok Permasalahan'),
            'objek_mediasi' => Yii::t('app', 'Objek Mediasi'),
            'proses_pertemuan' => Yii::t('app', 'Proses Pertemuan'),
            'id' => Yii::t('app', 'ID'),
            'created_date' => Yii::t('app', 'Created Date'),
            'modified_date' => Yii::t('app', 'Modified Date'),
            'finished' => Yii::t('app', 'Finished'),
            'berita_acara_filename' => Yii::t('app', 'Berita Acara'),
            'foto_filename' => Yii::t('app', 'Foto'),
            'surat_usulan_mediator_filename' => Yii::t('app', 'Surat Usulan Mediator'),
            'sk_mediator_filename' => Yii::t('app', 'SK Mediator'),
        ];
    }

    /**
     * @inheritdoc
     * @return PengaduanMediasiQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PengaduanMediasiQuery(get_called_class());
    }
}

pktha/pengaduan/backend/controllers/PengaduanMediasiController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\PengaduanMediasi;
use common\models\PengaduanMediasiSearch;
use common\models\PengaduanRegistrasi;
use common\utils\DateHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PengaduanMediasiController implements the CRUD actions for PengaduanMediasi model.
 */
class PengaduanMediasiController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors() 
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PengaduanMediasi models.
     *
     * @return mixed
     */
    public function actionIndex() 
    {
        $searchModel = new PengaduanMediasiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render(
            'index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
            ]
        );
    }

    /**
     * Displays a single PengaduanMediasi model.
     *
     * @param  string $id
     * @return mixed
     */
    public function actionView($id) 
    {
        $model = $this->findModel($id);
        $regModel = PengaduanRegistrasi::find()->getById($model->id_pengaduan);
        if (!Yii::$app->user->identity->isAdminWilayah($regModel->id_wilayah_konflik)) {
            throw new ServerErrorHttpException('You are not authorized to perform this action.');
        }

        return $this->render(
            'view', [
                    'model' => $model
            ]
        );
    }

    /**
     * Creates a new PengaduanMediasi model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate() 
    {
        $model = new PengaduanMediasi();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render(
                'create', [
                        'model' => $model,
                ]
            );
        }
    }

    /**
     * Updates an existing PengaduanMediasi model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param  string $id
     * @return mixed
     */
    public function actionUpdate($id) 
    {
        $model = $this->findModel($id);
        $regModel = PengaduanRegistrasi::find()->getById($model->id_pengaduan);
        if (!Yii::$app->user->identity->isAdminWilayah($regModel->id_wilayah_konflik)) {
            throw new ServerErrorHttpException('You are not authorized to perform this action.');
        }

        if ($model->load(Yii::$app->request->post())) {
            $model->modified_date = DateHelper::GetCurrentDate();
            if ($this->uploadModelFiles($model) && $model->save()) {
                return $this->redirect(['pengaduan-registrasi/view', 'id' => $model->id_pengaduan]);
            }
        } else {
            return $this->render(
                'update', [
                        'model' => $model,
                ]
            );
        }
    }

    /**
     * Cancels changes to Pengaduan model.
     *
     * @param  integer $id
     * @return mixed
     */
    public function actionCancel($id)
    {
        return $this->redirect(['pengaduan-registrasi/view', 'id' => PengaduanRegistrasi::find()->getById($this->findModel($id)->id_pengaduan)->id]);
    }

    /**
     * Uploads files found in the ActiveForm of this controller's view.
     *
     * @param  mixed reference to model to modify.
     * @return boolean indicating success/failure.
     * @throws ServerErrorHttpException if file could not be uploaded.
     */
    protected function uploadModelFiles($_model) 
    {
        $path = PengaduanRegistrasi::findOne(['id' => $_model->id_pengaduan])->getPath();
        /* It's probably safer to loop through a specified list of attributes
         * instead of through the full list of attributes. */
        $attrs = array('berita_acara', 'foto', 'surat_usulan_mediator', 'sk_mediator');

        foreach ($attrs as $key) {
            /* these variables rely on a naming convention of the form
             * [attr]_data and [attr]_filename for model files */
            $file_attr = $key . '_filename';
            $uploaded_file = UploadedFile::getInstance($_model, $file_attr);
            $subpath = $path . '/' . $key;
            if (!is_dir($subpath)) {
                mkdir($subpath, 0775, true);
            }
            if ($uploaded_file) {
                $name = $uploaded_file->baseName . '.' . $uploaded_file->extension;
                if ($uploaded_file->saveAs($subpath . '/' . $name)) {
                    $_model->$file_attr = $name;
                } else {
                    throw new ServerErrorHttpException($name . ' could not be uploaded.');
                }
            } // else attribute is not a file or no file uploaded
        }
        return true;
    }

    /**
     * Deletes an existing PengaduanMediasi model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param  string $id
     * @return mixed
     */
    public function actionDelete($id) 
    {
        $model = $this->findModel($id);
        $regModel = PengaduanRegistrasi::find()->getById($model->id_pengaduan);
        if (!Yii::$app->user->identity->isAdminWilayah($regModel->id_wilayah_konflik)) {
            throw new ServerErrorHttpException('You are not authorized to perform this action.');
        }
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Downloads the specified file type from a model.
     *
     * @param  string $id
     * @param  string $file type
     * @throws ServerErrorHttpException
     */
    public function actionDownload($id, $file)
    {
        $model = $this->findModel($id);
        $regModel = PengaduanRegistrasi::find()->getById($model->id_pengaduan);
        if (!Yii::$app->user->identity->isAdminWilayah($regModel->id_wilayah_konflik)) {
            throw new ServerErrorHttpException('You are not authorized to perform this action.');
        }
        $path = $regModel->getPath();

        switch ($file) {
        case 'berita_acara':
            $filename = $model->berita_acara_filename;
            break;
        case 'foto':
            $filename = $model->foto_filename;
            break;
        case 'surat_usulan_mediator':
            $filename = $model->surat_usulan_mediator_filename;
            break;
        case 'sk_mediator':
            $filename = $model->sk_mediator_filename;
            break;
        }

        if (isset($filename)) {
            $full_path = $path . '/' . $file . '/' . $filename;
            if (is_file($full_path)) {
                Yii:: $app->response->sendFile($full_path);
            } else {
                throw new ServerErrorHttpException($full_path . ' could not be found.');
            }
        }
    }

    /**
     * Finds the PengaduanMediasi model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param  string $id
     * @return PengaduanMediasi the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) 
    {
        if (($model = PengaduanMediasi::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

pktha/pengaduan/backend/views/pengaduan-mediasi/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\PengaduanMediasi */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pengaduan-mediasi-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?php echo $form->field($model, 'data_para_pihak')->textarea(['rows' => 6]) ?>

    <?php echo $form->field($model, 'berita_acara_filename')->fileInput(['multiple' => 6]) ?>

    <?php if ($model->berita_acara_filename) : ?>
        <?php echo Html::a($model->berita_acara_filename, ['pengaduan-mediasi/download', 'id' => $model->id, 'file' => 'berita_acara'], ['class' => 'btn bg-yellow']) ?>
    <?php endif ?>

    <?php echo $form->field($model, 'foto_filename')->fileInput(['multiple' => true]) ?>

    <?php if ($model->foto_filename) : ?>
        <?php echo Html::a($model->foto_filename, ['pengaduan-mediasi/download', 'id' => $model->id, 'file' => 'foto'], ['class' => 'btn bg-yellow']) ?>
    <?php endif ?>

    <?php echo $form->field($model, 'pokok_permasalahan')->textarea(['rows' => 6]) ?>

    <?php echo $form->field($model, 'objek_mediasi')->textarea(['rows' => 6]) ?>

    <?php echo $form->field($model, 'surat_usulan_mediator_filename')->fileInput(['multiple' => true]) ?>

    <?php if ($model->surat_usulan_mediator_filename) : ?>
        <?php echo Html::a($model->surat_usulan_mediator_filename, ['pengaduan-mediasi/download', 'id' => $model->id, 'file' => 'surat_usulan_mediator'], ['class' => 'btn bg-yellow']) ?>
    <?php endif ?>

    <?php echo $form->field($model, 'sk_mediator_filename')->fileInput(['multiple' => true]) ?>

    <?php if ($model->sk_mediator_filename) : ?>
        <?php echo Html::a($model->sk_mediator_filename, ['pengaduan-mediasi/download', 'id' => $model->id, 'file' => 'sk_mediator'], ['class' => 'btn bg-yellow']) ?>
    <?php endif ?>

    <?php echo $form->field($model, 'proses_pertemuan')->textarea(['rows' => 6]) ?>

    <?php echo $form->field($model, 'created_date')->textInput(['disabled' => true]) ?>

    <?php echo $form->field($model, 'modified_date')->textInput(['disabled' => true]) ?>

    <?php echo $form->field($model, 'finished')->checkbox() ?>

    <div class="form-group">
        <?php echo Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?php echo Html::a(Yii::t('app', 'Cancel'), ['cancel', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

pktha/pengaduan/backend/views/pengaduan-mediasi/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\PengaduanMediasiSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pengaduan-mediasi-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_pengaduan') ?>

    <?= $form->field($model, 'data_para_pihak') ?>

    <?= $form->field($model, 'berita_acara') ?>

    <?= $form->field($model, 'foto') ?>

    <?= $form->field($model, 'pokok_permasalahan') ?>

    <?php // echo $form->field($model, 'objek_mediasi') ?>

    <?php // echo $form->field($model, 'surat_usulan_mediator') ?>

    <?php // echo $form->field($model, 'sk_mediator') ?>

    <?php // echo $form->field($model, 'proses_pertemuan') ?>

    <?php // echo $form->field($model, 'id') ?>

    <?php // echo $form->field($model, 'created_date') ?>

    <?php // echo $form->field($model, 'modified_date') ?>

    <?php // echo $form->field($model, 'finished')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

pktha/pengaduan/backend/views/pengaduan-mediasi/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\PengaduanMediasi */

$this->title = Yii::t('app', 'Create Pengaduan Mediasi');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Pengaduan Mediasis'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pengaduan-mediasi-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

pktha/pengaduan/backend/views/pengaduan-mediasi/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel common\models\PengaduanMediasiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Pengaduan Mediasi');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pengaduan-mediasi-index">

    <?php Pjax::begin(); ?>    
    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'label' => 'Kode Pengaduan',
                'value' => function($model, $index, $widget) {
                    return common\models\PengaduanRegistrasi::find()->getById($model->id_pengaduan)->kode_pengaduan;
                }
            ],
            [
                'label' => 'Nama Pengadu',
                'value' => function($model, $index, $widget) {
                    return \common\models\PengaduanRegistrasi::findOne(['id' => $model->id_pengaduan])->nama_pengadu;
                }
            ],
            'data_para_pihak:ntext',
            // 'foto',
            'pokok_permasalahan:ntext',
            // 'objek_mediasi:ntext',
            // 'surat_usulan_mediator',
            // 'sk_mediator',
            // 'proses_pertemuan:ntext',
            // 'id',
            // 'created_date',
            // 'modified_date',
            // 'finished:boolean',
            [
                'label' => 'Status',
                'format' => 'html',
                'value' => function($model, $index, $widget) {
                    return $model->finished ? Html::a('Finished', '', ['class' => 'label bg-green']) : Html::a('Not Finished', '', ['class' => 'label bg-red']);
                }
            ],
            ['class' => 'yii\grid\ActionColumn',
                'template' => '{update}'],
        ],
    ]);
    ?>
    <?php Pjax::end(); ?></div>

pktha/pengaduan/backend/views/pengaduan-mediasi/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\PengaduanMediasi */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Pengaduan Mediasi',
]) . \common\models\PengaduanRegistrasi::findOne(['id' => $model->id_pengaduan])->kode_pengaduan;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Pengaduan Mediasi'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="pengaduan-mediasi-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

pktha/pengaduan/backend/views/pengaduan-mediasi/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\PengaduanMediasi */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Pengaduan Mediasis'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pengaduan-mediasi-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_pengaduan',
            'data_para_pihak:ntext',
            'berita_acara_data',
            'foto_data',
            'pokok_permasalahan:ntext',
            'objek_mediasi:ntext',
            'surat_usulan_mediator',
            'sk_mediator',
            'proses_pertemuan:ntext',
            'id',
            'created_date',
            'modified_date',
            'finished:boolean',
        ],
    ]) ?>

</div>